class Solution {
public:
    string intToRoman(int n) {
        string s="";        
        while(n>=1000){
            n=n-1000;
            s+="M";
        }
        while(n>=900){
            n=n-900;
            s+="CM";
        }
        while(n>=500){
            n=n-500;
            s+="D";
        }
        while(n>=400){
            n=n-400;
            s+="CD";
        }
        while(n>=100){
            n=n-100;
            s+="C";
        }
        while(n>=90){
            n=n-90;
            s+="XC";
        }
        while(n>=50){
            n=n-50;
            s+="L";
        }
        while(n>=40){
            n=n-40;
            s+="XL";
        }
        while(n>=10){
            n=n-10;
            s+="X";
        }
        while(n>=9){
            n=n-9;
            s+="IX";
        }
        while(n>=5){
            n=n-5;
            s+="V";
        }
        while(n>=4){
            n=n-4;
            s+="IV";
        }
        while(n>=1){
            n=n-1;
            s+="I";
        }
        return s;

    }
};